import { Fira_Code } from "next/font/google";
import Container from "react-bootstrap/Container";
import NavBar from "./components/NavBar";
import "./globals.css";

const inter = Fira_Code({
  weight: "300",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <NavBar />
          <main>{children}</main>
        </Container>
      </body>
    </html>
  );
}
